---

- include: mount.yml

- name: Install Prereq Packages
  yum:
    name: "{{ pckgs }}"
    state: latest

- name: Create Nifi Group
  group:
    name: "{{ nifi_grp }}"
    state: "present"
    gid: "{{ nifi_grp_id }}"

- name: Create Nifi User
  user:
    name: "{{ nifi_usr }}"
    state: "present"
    uid: "{{ nifi_usr_id }}"
    group: "{{ nifi_grp }}"
    comment: "Nifi Service Account"

- name: Copy zip file
  copy:
    src: "{{ nifi_instll_fl }}"
    dest: "{{ nifi_instll_flsystm }}"
    owner: "{{ nifi_usr }}"
    group: "{{ nifi_grp }}"

- name: Install Nifi
  unarchive:
    src: "{{ nifi_instll_flsystm }}/{{ nifi_instll_fl }}"
    dest: "{{ nifi_instll_flsystm }}"
    copy: no
    owner: "{{ nifi_usr }}"
    group: "{{ nifi_grp }}"
    creates: "{{ nifi_hm }}/README"
  notify: Restart Nifi

- name: Create SymLink
  file:
    src: "{{ nifi_instll_dr }}"
    dest: "{{ nifi_hm }}"
    state: link

- name: Create systemd Unit
  template:
    src: "nifi.service.j2"
    dest: "/etc/systemd/system/nifi.service"

- name: Modify Nifi Configuration
  replace:
    path: /app1/nifi-1.10.0/conf/bootstrap.conf
    regexp: "java.arg.2=-Xms512m"
    replace: "{{ java_heap_2 }}"

- name: Modify Nifi Configuration
  replace:
    path: /app1/nifi-1.10.0/conf/bootstrap.conf
    regexp: "java.arg.3=-Xmx512m"
    replace: "{{ java_heap_3 }}"

- name: Modify Nifi Configuration
  replace:
    path: /app1/nifi-1.10.0/conf/nifi.properties
    regexp: "nifi.queue.backpressure.count=10000"
    replace: "{{ backpressure_count }}"

- name: Modify Nifi Configuration
  replace:
    path: /app1/nifi-1.10.0/conf/nifi.properties
    regexp: "nifi.queue.backpressure.size=1 GB"
    replace: "{{ backpressure_size }}"
