---
# tasks file for mount

- name: Ensure mount directory exists.
  file:
    path: "{{ efs_mount_dir }}"
    state: directory
    mode: 0755

- name: Ensure EFS volume is mounted.
  mount:
    name: "{{ efs_mount_dir }}"
    src: "{{ mount_target_ip }}"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev
    state: mounted
